generate jest report

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -62,6 +62,13 @@ jobs:
         run: |
           npm run test
 
+      - name: upload jest test results
+        uses: actions/upload-artifact@v2 # upload test results
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: test-results
+          path: jest-junit.xml
+
       - name: 📝 update CHANGELOG.md
         run: |
           npm run update-changelog
